"""
Prompt templates for the AI Flight Planner.

All prompts are designed for LLM-based aviation route planning:
  - NLP Parser: natural language → structured routing parameters
  - Route Evaluator: ranks K candidate routes by quality
"""
import json


# ---------------------------------------------------------------------------
# NLP Parser prompt — extracts structured intent from free-text input
# ---------------------------------------------------------------------------

NLP_PARSER_SYSTEM = """You are an aviation route planning assistant. Extract structured routing parameters from the user's natural language input. Output ONLY valid JSON, no markdown, no explanation.

Return a JSON object with these fields:
{
  "origin": "Departure airport ICAO code (4 letters, uppercase)",
  "destination": "Arrival airport ICAO code (4 letters, uppercase)",
  "airway_type": "J (high-altitude jet) | B (low-altitude) | V (Victor, low-altitude) | null (any)",
  "avoid_waypoints": ["Waypoint idents to avoid", ...],
  "avoid_airspaces": ["Airspace names to avoid", ...],
  "prefer_sid": "Preferred SID name (e.g., RAME1C, BEKO3A) or null",
  "prefer_star": "Preferred STAR name (e.g., SIER7A, ABEY3B) or null",
  "cruise_altitude": cruise altitude in feet (integer) or null,
  "confidence": confidence score 0.0-1.0
}

Rules:
- Map city/airport names to ICAO codes (e.g., "Hong Kong" → "VHHH", "Tokyo" → "RJTT")
- "high altitude" / "upper" / "jet" → airway_type "J"
- "low altitude" / "lower" / "victor" → airway_type "V" or "B"
- If the user mentions a specific SID by name (e.g., "OCEAN1", "RAME1C"), set prefer_sid to that name
- If the user mentions a specific STAR by name (e.g., "SIER7A"), set prefer_star to that name
- "departure via XXX" or "SID XXX" or "離場走XXX" → prefer_sid "XXX"
- "arrival via XXX" or "STAR XXX" or "進場走XXX" → prefer_star "XXX"
- If the user mentions a waypoint to avoid, use the exact ident
- Set confidence to 0.0 if you cannot determine origin or destination
- Do NOT invent waypoint or airway names that aren't mentioned
- If you're unsure about a field, set it to null
"""


def build_nlp_parser_prompt(user_input: str) -> list[dict[str, str]]:
    """Build messages for the NLP parser LLM call."""
    return [
        {"role": "system", "content": NLP_PARSER_SYSTEM},
        {"role": "user", "content": user_input[:500]},  # truncate to 500 chars
    ]


# ---------------------------------------------------------------------------
# Route Evaluator prompt — ranks K candidate routes
# ---------------------------------------------------------------------------

ROUTE_EVALUATOR_SYSTEM = """You are a senior airline dispatcher evaluating flight routes.

You will receive K candidate routes between {origin} and {destination}.
Each route was generated by a shortest-path algorithm using real airway data.
Rank them from best (1) to worst (K) based on:

1. **Distance** — shorter is better (weight: 40%)
2. **Airway continuity** — fewer airway changes is better (weight: 30%)
3. **User preferences** — respect any constraints the user specified (weight: 30%)

User preferences: {user_preferences}

Output ONLY valid JSON:
{{
  "rankings": [
    {{"index": 0, "score": 8.5, "reason": "Shortest distance, good airway continuity, complies with all preferences"}},
    ...
  ],
  "best_index": 0
}}

Score is 1.0-10.0 (higher is better). The "reason" should be 1-2 sentences in the same language as the user's input."""
# Note: The {origin}, {destination}, and {user_preferences} placeholders
# are filled at runtime.


def build_evaluator_prompt(
    origin: str,
    destination: str,
    candidates: list[dict],
    user_preferences: str = "",
) -> list[dict[str, str]]:
    """
    Build messages for the route evaluator LLM call.

    Args:
        origin: Origin airport ICAO.
        destination: Destination airport ICAO.
        candidates: List of candidate summaries, each with {index, route_string, distance_nm, segment_count}.
        user_preferences: Natural language user preferences/constraints.
    """
    system = ROUTE_EVALUATOR_SYSTEM.format(
        origin=origin,
        destination=destination,
        user_preferences=user_preferences or "None specified — prefer shortest distance",
    )

    # Build candidate summary text
    candidate_text = []
    for c in candidates:
        candidate_text.append(
            f"Route #{c['index']}: {c['route_string']}\n"
            f"  Distance: {c['distance_nm']:.0f} NM\n"
            f"  Segments: {c['segment_count']}\n"
        )

    user_msg = (
        f"Please evaluate these {len(candidates)} routes from {origin} to {destination}:\n\n"
        + "\n".join(candidate_text)
    )

    return [
        {"role": "system", "content": system},
        {"role": "user", "content": user_msg},
    ]
